name: Build release

permissions:
  contents: write

on: push

#on:
#  push:
#    tags:
#      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - path: ./target/release/rust_todo_server
          - path: ./target/release/rust_todo_server.exe
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@master
        with:
          name: rust_todo_server-${{ matrix.os }}
          path: ${{ matrix.path }}