name: Build release

permissions:
  contents: write

on: push

#on:
#  push:
#    tags:
#      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        - os: ubuntu-latest
          path: ./target/release/rust_todo_server
        - os: macos-latest
          path: ./target/release/rust_todo_server
        - os: windows-latest
          path: ./target/release/rust_todo_server.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@master
        with:
          name: rust_todo_server-${{ matrix.os }}
          path: ${{ matrix.path }}