name: Build release

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    name: Build app for ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        include:
          - path: ./target/release/rust_todo_server
            ext:
          - path: ./target/release/rust_todo_server.exe
            ext: .exe
            os: windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@master
        with:
          name: rust_todo_server-${{ matrix.os }}
          path: ${{ matrix.path }}
      - run: mv ${{ matrix.path }} ./rust_todo_server-${{ matrix.os }}${{ matrix.ext }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rust_todo_server-${{ matrix.os }}${{ matrix.ext }}